FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*"}

[Project]
Name = "examples"
TargetType = "BeefGUIApplication"
StartupObject = "raylib_beef.examples.Core.Program"
DefaultNamespace = "raylib_beef.examples"
